name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: jikuma/githubaction@v7-release-dev
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Release from Test'
        release_note: 'Release created from commit ${{ github.sha }}'
        asset_filepath: './README.md'
        tag_name: v0.1.GITHUB_SHORT_SHA
    - uses: jikuma/githubaction@v7-release-dev
      with:
        operation: 'upload an asset to a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        asset_filepath: './CHANGELOG.md'
        tag_name: v0.1.GITHUB_SHORT_SHA
